In [3]:
import numpy as np 

In [5]:
my_list=[1,2,3,4]
print(type(my_list))

<class 'list'>


In [8]:
#cast list as array
arr=np.array(my_list)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
#create an array using range function 
my_arr=np.arange(0,11)
print(my_arr)
my_arr2=np.arange(0,11,2)
print(my_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [12]:
#create zeros and ones array and it returns float values

zeros_arr=np.zeros((3,6))
print(zeros_arr)

ones_arr=np.ones((3,6))
print(ones_arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
#get same random value everytime using seed

np.random.seed(101)
rand_arr=np.random.randint(0,100,10)
print(rand_arr)


rand_arr2=np.random.randint(0,100,10)
print(rand_arr2)



[95 11 81 70 63 87 75  9 77 40]
[ 4 63 40 60 92 64  5 12 93 40]


In [18]:
#find min,max,ardmax(),argmin(),mean,shape
rand_arr.max()



95

In [19]:
rand_arr.argmax()

0

In [20]:
rand_arr.min()

9

In [21]:
rand_arr.argmin()

7

In [22]:
rand_arr.mean()

60.8

In [23]:
rand_arr.shape

(10,)

In [24]:
rand_arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [37]:
#create a matrix

matrix=np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
#get desired value from matrix
row=6
col=5
matrix[row,col]


65

In [39]:
#grab all items in col and row using slicing 

In [40]:
matrix[:,2] #all items of col2

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [44]:
matrix[3,:]  #all items of row3

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [46]:
matrix[4:8,2:7]

array([[42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66],
       [72, 73, 74, 75, 76]])

In [48]:
#copy matrix 
my_copy=matrix.copy()
my_copy


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])